"""
Batch driver for generating Ch 7–30 of the Journey mode (96 new levels).
Each level is generated by invoking `pixel_level_pipeline.py build-level --pixellab`.
Already-generated levels (JSON exists) are skipped so the script is idempotent.

Run:
    source .venv-pixellab/bin/activate
    PIXELLAB_SECRET=<key> python3 Scripts/build_journey_30.py
"""
from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LEVELS_DIR = REPO / "PixelColoringGame" / "Resources" / "Levels"
OUTPUT_FOLDER = REPO / "PixelColoringGame" / "Resources"
PIPELINE = REPO / "Scripts" / "pixel_level_pipeline.py"

DIFFICULTY_PRESETS = {
    "Easy":   {"board": 24, "colors": 4, "minutes": 4, "preset": "simple-sticker"},
    "Medium": {"board": 28, "colors": 5, "minutes": 6, "preset": "simple-sticker"},
    "Hard":   {"board": 32, "colors": 6, "minutes": 8, "preset": "soft-toy"},
}

# Chapter 7-30 definitions.  Each item: (chapter_id, difficulty, levels=[(level_id, title, category, prompt_motif)])
CHAPTERS: list[dict] = [
    # ---- Easy (Ch 7-14) ----
    {"ch": "dawn-petal", "diff": "Easy", "levels": [
        ("sakura",      "Sakura Bloom",     "plants",  "sakura cherry blossom, five round petals, soft pink and cream"),
        ("hummingbird", "Tiny Hummingbird", "animals", "hummingbird in flight, iridescent teal and rose"),
        ("bunny",       "Spring Bunny",     "animals", "sitting bunny rabbit, soft beige and peach"),
        ("robin",       "Red Robin",        "animals", "round robin bird with red breast, warm brown and cream"),
    ]},
    {"ch": "dewy-meadow", "diff": "Easy", "levels": [
        ("clover",    "Lucky Clover",   "plants",  "three-leaf clover, vivid meadow green"),
        ("ladybug",   "Polka Ladybug",  "animals", "ladybug top-down, deep red with black polka dots"),
        ("dandelion", "Dandelion Puff", "plants",  "dandelion seed puff, pale cream and sage"),
        ("dragonfly", "Glass Dragonfly","animals", "dragonfly with wings spread, turquoise and icy blue"),
    ]},
    {"ch": "rainbow-puddle", "diff": "Easy", "levels": [
        ("raindrop", "Raindrop",      "objects", "single large raindrop, cobalt and sky blue"),
        ("umbrella", "Yellow Umbrella","objects", "open umbrella top view, sunny yellow and white"),
        ("rainbow",  "Arc Rainbow",   "objects", "rainbow arc five stripes, clean bright colors"),
        ("frog",     "Pond Frog",     "animals", "chubby frog sitting, leafy green and pale yellow"),
    ]},
    {"ch": "spring-basket", "diff": "Easy", "levels": [
        ("carrot",      "Garden Carrot", "food",    "carrot with green leaves, warm orange and emerald"),
        ("radish",      "Pink Radish",   "food",    "red radish with white tip, bright magenta and cream"),
        ("peapod",      "Peapod",        "food",    "open peapod with three peas, soft garden green"),
        ("speckledegg", "Speckled Egg",  "objects", "speckled egg, pale robin-blue with brown specks"),
    ]},
    {"ch": "sunflower-field", "diff": "Easy", "levels": [
        ("sunflower",    "Sunflower",      "plants",  "sunflower front view, golden petals and chocolate center"),
        ("honeyjar",     "Honey Jar",      "food",    "jar of honey with dipper, amber gold and cream"),
        ("bumblebee",    "Bumblebee",      "animals", "plump bumblebee, warm yellow and black stripes"),
        ("picnicbasket", "Picnic Basket",  "objects", "woven picnic basket with red check cloth, tan and red"),
    ]},
    {"ch": "citrus-grove", "diff": "Easy", "levels": [
        ("lemon",     "Fresh Lemon",    "food", "whole lemon with leaf, bright yellow and green"),
        ("orange",    "Ripe Orange",    "food", "whole orange fruit, rich orange and leaf green"),
        ("lime",      "Lime Wedge",     "food", "lime with leaf, vivid lime green"),
        ("tangerine", "Mini Tangerine", "food", "small tangerine with stem, soft orange and sage leaf"),
    ]},
    {"ch": "melon-patch", "diff": "Easy", "levels": [
        ("watermelon", "Watermelon Slice","food", "triangular watermelon slice, red with green rind"),
        ("cantaloupe", "Cantaloupe Half", "food", "halved cantaloupe melon, peach and cream"),
        ("grapevine",  "Grape Bunch",     "food", "cluster of purple grapes with leaf, violet and green"),
        ("peach",      "Summer Peach",    "food", "peach fruit with leaf, soft pink and warm peach"),
    ]},
    {"ch": "sandy-cove", "diff": "Easy", "levels": [
        ("crab",       "Little Crab",     "animals", "small crab facing front, coral and warm pink"),
        ("sandcastle", "Sandcastle",      "objects", "tiny sandcastle with flag, warm sand and turquoise flag"),
        ("beachball",  "Beach Ball",      "objects", "round beach ball, bright red blue and yellow segments"),
        ("sunhat",     "Straw Sun Hat",   "objects", "floppy straw sun hat with ribbon, tan and sky blue"),
    ]},
    # ---- Medium (Ch 15-22) ----
    {"ch": "autumn-orchard", "diff": "Medium", "levels": [
        ("pumpkin",    "Round Pumpkin", "food",    "round pumpkin with stem and leaf, bright orange and forest green"),
        ("mapleleaf",  "Maple Leaf",    "plants",  "maple leaf five points, fiery red and golden yellow"),
        ("chestnut",   "Fresh Chestnut","food",    "chestnut nut with burr, glossy brown and spiky tan"),
        ("persimmon",  "Persimmon",     "food",    "persimmon fruit with leaf, sunset orange and green"),
    ]},
    {"ch": "harvest-table", "diff": "Medium", "levels": [
        ("breadloaf",   "Rustic Bread",  "food",    "round crusty bread loaf, warm tan and cream"),
        ("cheesewheel", "Cheese Wheel",  "food",    "wheel of cheese with slice, golden yellow and pale cream"),
        ("grapes",      "Grape Cluster", "food",    "cluster of red grapes with stem, wine red and green leaf"),
        ("honeypot",    "Honey Pot",     "food",    "ceramic honey pot with dipper, ochre and warm brown"),
    ]},
    {"ch": "forest-sprigs", "diff": "Medium", "levels": [
        ("fernscroll",  "Fiddlehead Fern","plants",  "curled fern fiddlehead, spring green and cream"),
        ("pinecone",    "Pine Cone",     "plants",  "pine cone closed, warm brown and golden tan"),
        ("hazelnut",    "Hazelnut",      "food",    "hazelnut with husk, chestnut brown and sage"),
        ("wildberry",   "Wild Berry",    "food",    "cluster of wild berries on branch, raspberry red and leaf green"),
    ]},
    {"ch": "tea-garden", "diff": "Medium", "levels": [
        ("teapot",    "Teapot",      "objects", "ceramic teapot with steam, sky blue and cream"),
        ("scone",     "Cream Scone", "food",    "round scone with cream and jam, golden brown and ruby"),
        ("matchacup", "Matcha Cup",  "food",    "bowl of matcha tea, jade green and cream"),
        ("cookietin", "Cookie Tin",  "objects", "decorative cookie tin with ribbon, rose pink and gold"),
    ]},
    {"ch": "snowy-grove", "diff": "Medium", "levels": [
        ("snowflake",  "Big Snowflake","objects", "six-point snowflake, icy white and pale blue"),
        ("wintercone", "Frost Cone",  "plants",  "frosted pine cone, soft brown with white frost"),
        ("cardinal",   "Winter Cardinal","animals","red cardinal bird on branch, vivid red and dark brown"),
        ("evergreen",  "Evergreen Tree","plants", "pointed evergreen tree with snow, forest green and white"),
    ]},
    {"ch": "cozy-hearth", "diff": "Medium", "levels": [
        ("mitten",       "Knit Mitten",  "objects", "knitted mitten, cherry red and cream cable"),
        ("candle",       "Lit Candle",   "objects", "pillar candle with flame, cream white and warm gold flame"),
        ("cocoacup",     "Cocoa Mug",    "food",    "mug of cocoa with marshmallow, warm brown and cream"),
        ("cinnamonroll", "Cinnamon Roll","food",    "round cinnamon roll with icing, golden brown and white glaze"),
    ]},
    {"ch": "gingerbread-lane", "diff": "Medium", "levels": [
        ("gingerman",   "Gingerbread Person","food", "gingerbread figure with icing, warm tan and white icing"),
        ("candycane",   "Candy Cane",        "food", "red and white candy cane, bright red and pure white"),
        ("peppermint",  "Peppermint Swirl",  "food", "round peppermint candy, white with red swirl"),
        ("frostedbun",  "Frosted Bun",       "food", "iced bun with sprinkles, warm cream and rainbow sprinkles"),
    ]},
    {"ch": "icy-pond", "diff": "Medium", "levels": [
        ("iceskate",    "Ice Skate",     "objects", "white ice skate with laces, cream and silver blade"),
        ("snowball",    "Snowball",      "objects", "round packed snowball, pure white with pale blue shadows"),
        ("winterberry", "Winterberry Sprig","plants","sprig of red berries with leaves, scarlet and holly green"),
        ("snowowl",     "Snowy Owl",     "animals", "snowy owl front view, white with charcoal flecks"),
    ]},
    # ---- Hard (Ch 23-30) ----
    {"ch": "yarn-nook", "diff": "Hard", "levels": [
        ("yarnball",   "Ball of Yarn",  "objects", "ball of yarn with loose strand, soft rose pink and cream"),
        ("knittedhat", "Knitted Hat",   "objects", "pom-pom knit beanie, mustard yellow and burgundy stripe"),
        ("sweater",    "Cozy Sweater",  "objects", "folded knit sweater, slate blue with cable pattern"),
        ("teacozy",    "Tea Cozy",      "objects", "knit tea cozy over teapot, cream and olive green"),
    ]},
    {"ch": "bookshelf-corner", "diff": "Hard", "levels": [
        ("bookstack",   "Stack of Books","objects", "stack of three books, teal wine and ochre spines"),
        ("readinglamp", "Reading Lamp",  "objects", "banker-style desk lamp, green shade and brass base"),
        ("bookmark",    "Tassel Bookmark","objects","tasseled bookmark on a page, ruby red with gold tassel"),
        ("sleepycat",   "Sleepy Cat",    "animals", "cat curled asleep, ginger tabby and cream belly"),
    ]},
    {"ch": "art-studio", "diff": "Hard", "levels": [
        ("painttube",  "Paint Tube",   "objects", "squeezed paint tube, magenta paint and silver tube"),
        ("paintbrush", "Paintbrush",   "objects", "paintbrush with paint tip, oak handle and cobalt paint"),
        ("palette",    "Paint Palette","objects", "artist palette with colorful blobs, wood brown and rainbow dots"),
        ("easel",      "Mini Easel",   "objects", "wooden easel with small canvas, warm tan and cream canvas"),
    ]},
    {"ch": "music-nook", "diff": "Hard", "levels": [
        ("musicnote",  "Music Note",   "objects", "eighth note symbol, deep navy with subtle highlight"),
        ("ukulele",    "Ukulele",      "objects", "small ukulele front view, warm wood and silver strings"),
        ("tambourine", "Tambourine",   "objects", "round tambourine with jingles, red wood and gold jingles"),
        ("gramophone", "Old Gramophone","objects","vintage gramophone horn, brass gold and dark wood"),
    ]},
    {"ch": "firefly-glen", "diff": "Hard", "levels": [
        ("firefly",     "Glowing Firefly", "animals", "firefly in flight with glow, charcoal body and warm yellow glow"),
        ("mushroomlamp","Mushroom Lamp",   "plants",  "glowing mushroom cap, soft indigo and warm yellow glow"),
        ("glowpetal",   "Glow Petal",      "plants",  "single glowing flower petal, lavender and pale gold"),
        ("mothglow",    "Luna Moth",       "animals", "luna moth wings spread, pale mint green and cream"),
    ]},
    {"ch": "constellation-sky", "diff": "Hard", "levels": [
        ("starcluster",  "Star Cluster",   "objects", "cluster of three stars, bright gold on deep indigo"),
        ("comet",        "Shooting Comet", "objects", "comet with tail, cream head and cyan-white tail"),
        ("ringedplanet", "Ringed Planet",  "objects", "saturn-like planet with rings, warm beige and cream rings"),
        ("crescentmoon", "Crescent Moon",  "objects", "crescent moon with tiny stars, pale yellow and cream"),
    ]},
    {"ch": "dream-pillow", "diff": "Hard", "levels": [
        ("pillow",      "Soft Pillow",    "objects", "fluffy pillow with tassels, soft lavender and cream tassel"),
        ("plushbunny",  "Plush Bunny",    "objects", "stuffed bunny toy, cream with pink inner ears"),
        ("starmobile",  "Star Mobile",    "objects", "hanging star mobile three stars, pale blue and cream thread"),
        ("nightlight",  "Cozy Nightlight","objects", "glowing crescent nightlight, soft peach and cream glow"),
    ]},
    {"ch": "fairy-hollow", "diff": "Hard", "levels": [
        ("mushroomhouse","Mushroom House","plants",  "tiny mushroom house with door, scarlet cap and cream stem"),
        ("fairywing",    "Fairy Wing",    "objects", "single iridescent fairy wing, soft pink and pale violet"),
        ("dewberry",     "Dew Berry",     "food",    "cluster of dewy berries, rich purple and leaf green"),
        ("toadstool",    "Toadstool",     "plants",  "classic red toadstool with white dots, red cap and cream stem"),
    ]},
]


def level_specs():
    """Yield (order, level_id, title, category, difficulty, prompt_motif) for each level."""
    order = 25  # sortOrder starts at 25 (after existing 24 levels)
    for ch in CHAPTERS:
        diff = ch["diff"]
        for (lid, title, cat, motif) in ch["levels"]:
            yield (order, lid, title, cat, diff, motif)
            order += 1


def build_prompt(motif: str) -> str:
    return (
        f"simple {motif} sticker, centered, chunky pixel art, "
        "very readable silhouette, no background, no text, no extra details"
    )


def main():
    failures = []
    generated = 0
    skipped = 0
    total = sum(len(ch["levels"]) for ch in CHAPTERS)

    for (order, lid, title, cat, diff, motif) in level_specs():
        json_path = LEVELS_DIR / f"{lid}.json"
        if json_path.exists():
            skipped += 1
            print(f"[{order:3}/{24 + total}] skip {lid} (already exists)")
            continue

        preset = DIFFICULTY_PRESETS[diff]
        cmd = [
            sys.executable, str(PIPELINE), "build-level", "--pixellab",
            "--prompt", build_prompt(motif),
            "--level-id", lid,
            "--title", title,
            "--title-key", f"level.{lid}.title",
            "--category", cat,
            "--category-key", f"level.category.{cat}",
            "--difficulty", diff,
            "--difficulty-key", f"level.difficulty.{diff.lower()}",
            "--estimated-minutes", str(preset["minutes"]),
            "--sort-order", str(order),
            "--board-size", str(preset["board"]),
            "--max-colors", str(preset["colors"]),
            "--style-preset", preset["preset"],
            "--output-folder", str(OUTPUT_FOLDER),
        ]
        t0 = time.time()
        print(f"[{order:3}/{24 + total}] gen  {lid} ({diff}, {cat}) ...", flush=True)
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            if result.returncode != 0:
                raise RuntimeError(f"exit {result.returncode}: {result.stderr[-400:]}")
            dt = time.time() - t0
            print(f"    ok  in {dt:.1f}s")
            generated += 1
        except Exception as exc:
            dt = time.time() - t0
            print(f"    FAIL in {dt:.1f}s: {exc}")
            failures.append((lid, str(exc)))

    print("\n=== summary ===")
    print(f"generated: {generated}")
    print(f"skipped:   {skipped}")
    print(f"failed:    {len(failures)}")
    if failures:
        for (lid, err) in failures:
            print(f"  - {lid}: {err[:200]}")
        sys.exit(1)


if __name__ == "__main__":
    main()
