#!/usr/bin/env python3
"""Patch Localizable.xcstrings to add en + ja entries for all daily challenge content.

This addresses ~439 keys that the JSON daily catalog and daily level manifests
reference (e.g. "Monthly Daily", "Snowy keepsakes, ...", "Sled", "Easy") but
which were never added to Localizable.xcstrings. As a result every locale (incl.
Japanese) shows the English source string.

We add a minimal en + ja entry per key. Other locales fall back to en via the
project's existing AppLocalization fallback chain.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent / "PixelColoringGame" / "Resources"
xc_path = root / "Localizable.xcstrings"

# ----- Catalog-level translations -----
TRANSLATIONS_JA: dict[str, str] = {
    # Catalog top-level
    "Monthly Daily": "今月のデイリー",
    "A fresh hand-picked pixel artwork every day.": "毎日ひとつ、選び抜かれたピクセルアート。",
    "Monthly Album": "今月のアルバム",

    # 12 month titles
    "January Daily": "1月のデイリー",
    "February Daily": "2月のデイリー",
    "March Daily": "3月のデイリー",
    "April Daily": "4月のデイリー",
    "May Daily": "5月のデイリー",
    "June Daily": "6月のデイリー",
    "July Daily": "7月のデイリー",
    "August Daily": "8月のデイリー",
    "September Daily": "9月のデイリー",
    "October Daily": "10月のデイリー",
    "November Daily": "11月のデイリー",
    "December Daily": "12月のデイリー",

    # 12 banners
    "Snowy keepsakes, lucky charms, and warm winter starts.": "雪の思い出と縁起物、あたたかな冬のはじまり。",
    "Sweet hearts, cocoa breaks, and soft winter affection.": "甘いハート、ココアのひととき、やさしい冬の愛情。",
    "Buds, blossoms, and gentle spring beginnings.": "つぼみと花、やさしい春のはじまり。",
    "Fresh notebooks, flower trails, and bright new starts.": "新しいノート、花の小道、まぶしい新生活のはじまり。",
    "Picnic skies, young leaves, and cheerful holiday signs.": "ピクニック日和の空、若葉、楽しい祝日の合図。",
    "Raindrops, hydrangeas, and slow cozy rainy days.": "雨つぶ、あじさい、ゆっくり過ごす雨の日。",
    "Stars, festival lights, and sparkling summer nights.": "星、祭りのあかり、きらめく夏の夜。",
    "Sea breeze, sunflowers, and playful vacation memories.": "潮風、ひまわり、にぎやかな夏休みの思い出。",
    "Moonlit sweets, reading corners, and early autumn calm.": "月夜のおやつ、読書スペース、初秋の静けさ。",
    "Pumpkins, candy trails, and playful midnight surprises.": "かぼちゃ、お菓子の小道、ちょっと不思議な真夜中。",
    "Maple warmth, mushrooms, and soft amber evenings.": "もみじのぬくもり、きのこ、琥珀色の夕暮れ。",
    "Snow bells, gift ribbons, and bright holiday glow.": "雪のすず、ギフトのリボン、まばゆい年末のかがやき。",

    # 12 archive titles
    "January Archive": "1月のアーカイブ",
    "February Archive": "2月のアーカイブ",
    "March Archive": "3月のアーカイブ",
    "April Archive": "4月のアーカイブ",
    "May Archive": "5月のアーカイブ",
    "June Archive": "6月のアーカイブ",
    "July Archive": "7月のアーカイブ",
    "August Archive": "8月のアーカイブ",
    "September Archive": "9月のアーカイブ",
    "October Archive": "10月のアーカイブ",
    "November Archive": "11月のアーカイブ",
    "December Archive": "12月のアーカイブ",

    # 12 archive subtitles
    "Revisit January's cozy New Year collection.": "1月の心あたたまるお正月コレクションをもう一度。",
    "Revisit February's sweet and snowy collection.": "2月の甘く雪化粧したコレクションをもう一度。",
    "Revisit March's blossom and farewell collection.": "3月の花咲く別れのコレクションをもう一度。",
    "Revisit April's bright and breezy collection.": "4月の明るくさわやかなコレクションをもう一度。",
    "Revisit May's picnic and fresh-leaf collection.": "5月のピクニックと新緑のコレクションをもう一度。",
    "Revisit June's rainy-season collection.": "6月の梅雨コレクションをもう一度。",
    "Revisit July's starry summer collection.": "7月の星降る夏コレクションをもう一度。",
    "Revisit August's beach and festival collection.": "8月のビーチとお祭りコレクションをもう一度。",
    "Revisit September's moon-viewing collection.": "9月のお月見コレクションをもう一度。",
    "Revisit October's Halloween collection.": "10月のハロウィンコレクションをもう一度。",
    "Revisit November's harvest collection.": "11月の実りのコレクションをもう一度。",
    "Revisit December's holiday collection.": "12月のホリデーコレクションをもう一度。",

    # 12 reward titles (event titles)
    "January Dreamer": "新年の夢みびと",
    "Heart Keeper": "想いを守るひと",
    "Spring Song": "春のしらべ",
    "Bloom Scout": "花めぐりびと",
    "Leaf Chaser": "若葉の追跡者",
    "Rain Walker": "雨を歩むひと",
    "Wish Lantern": "願いの灯ろう",
    "Sun Tide": "陽光の潮",
    "Moon Reader": "月読みびと",
    "Candy Phantom": "キャンディの幻影",
    "Amber Trail": "琥珀の小道",
    "Winter Bell": "冬のすず",

    # 12 reward subtitles (unlock messages)
    "Complete every January artwork to unlock this title.": "1月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every February artwork to unlock this title.": "2月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every March artwork to unlock this title.": "3月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every April artwork to unlock this title.": "4月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every May artwork to unlock this title.": "5月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every June artwork to unlock this title.": "6月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every July artwork to unlock this title.": "7月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every August artwork to unlock this title.": "8月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every September artwork to unlock this title.": "9月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every October artwork to unlock this title.": "10月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every November artwork to unlock this title.": "11月の作品をすべて完成させて、この称号を解放しよう。",
    "Complete every December artwork to unlock this title.": "12月の作品をすべて完成させて、この称号を解放しよう。",

    # Difficulties
    "Easy": "かんたん",
    "Medium": "ふつう",
    "Hard": "むずかしい",

    # Categories
    "Animals": "どうぶつ",
    "Food": "たべもの",
    "Objects": "もの",
    "Plants": "しょくぶつ",
    "Seasonal": "きせつ",

    # Level titles (alphabetized)
    "Acorn Basket": "どんぐりバスケット",
    "Acorn Mug": "どんぐりマグ",
    "Amber Candle": "琥珀のキャンドル",
    "Angel Bell": "エンジェルベル",
    "Apple Juice": "りんごジュース",
    "Autumn Bat": "秋のこうもり",
    "Autumn Jam": "秋のジャム",
    "Autumn Leaf Pin": "もみじピン",
    "Bamboo Branch": "竹の枝",
    "Bamboo Flute": "竹笛",
    "Bat Candy": "こうもりキャンディ",
    "Beach Bucket": "ビーチバケツ",
    "Beach Sandal": "ビーチサンダル",
    "Beach Umbrella": "ビーチパラソル",
    "Berry Tart": "ベリータルト",
    "Bike Bell": "自転車のベル",
    "Birdhouse": "巣箱",
    "Black Cat": "くろねこ",
    "Bloom Basket": "花のバスケット",
    "Blossom Bento": "花見べんとう",
    "Blossom Jam": "花のジャム",
    "Blossom Teacup": "花のティーカップ",
    "Blue Sky Kite": "青空のたこ",
    "Blue Umbrella": "青いかさ",
    "Blush Heart": "ほおを染めるハート",
    "Bon Dance Drum": "盆踊り太鼓",
    "Book Lamp": "ブックランプ",
    "Broom Ribbon": "ほうきのリボン",
    "Bud Vase": "つぼみの花瓶",
    "Bug Net": "虫あみ",
    "Bunny Pencil": "うさぎ鉛筆",
    "Butterfly Net": "蝶の捕虫網",
    "Camp Lantern": "キャンプランタン",
    "Canary": "カナリア",
    "Candy Bucket": "キャンディバケツ",
    "Candy Cane": "キャンディケーン",
    "Candy Corn Bag": "キャンディコーンの袋",
    "Candy Jar": "キャンディの瓶",
    "Caramel Apple": "キャラメルりんご",
    "Carp Streamer": "こいのぼり",
    "Carrot Cake": "にんじんケーキ",
    "Cedar Branch": "杉の枝",
    "Checkered Lunchbox": "チェック柄のお弁当箱",
    "Cherry Notebook": "さくらノート",
    "Cherry Parfait": "さくらんぼパフェ",
    "Cherry Sundae": "さくらんぼサンデー",
    "Cherry Truffle": "さくらんぼトリュフ",
    "Chestnut Cup": "栗のカップ",
    "Chestnut Tart": "栗のタルト",
    "Chocolate Pretzel": "チョコプレッツェル",
    "Choir Bird": "聖歌隊の鳥",
    "Christmas Tree": "クリスマスツリー",
    "Cloud Pouch": "雲のポーチ",
    "Cloud Rabbit": "雲のうさぎ",
    "Cloud Sheep": "雲のひつじ",
    "Cloud Whale": "雲のくじら",
    "Clover Brooch": "クローバーのブローチ",
    "Clover Cap": "クローバー帽子",
    "Clover Frog": "クローバーかえる",
    "Clover Windmill": "クローバー風車",
    "Cocoa Cup": "ココアカップ",
    "Cocoa Mitten": "ココア色のミトン",
    "Cocoa Mug": "ココアマグ",
    "Coffee Bean Pouch": "コーヒー豆の袋",
    "Comet Ribbon": "彗星のリボン",
    "Confetti Bow": "紙ふぶきの蝶結び",
    "Confetti Hat": "紙ふぶき帽子",
    "Constellation Map": "星座マップ",
    "Coral Pin": "サンゴのピン",
    "Cosmos Pin": "コスモスのピン",
    "Cotton Candy": "わたあめ",
    "Cozy Blanket": "コージーブランケット",
    "Cozy Mittens": "コージーミトン",
    "Cozy Socks": "コージーソックス",
    "Cozy Sweater": "コージーセーター",
    "Crane Charm": "つるのお守り",
    "Cricket Lantern": "鈴虫ランタン",
    "Daffodil": "ラッパすいせん",
    "Dahlia": "ダリア",
    "Dandelion Cup": "たんぽぽカップ",
    "Daruma": "だるま",
    "Deer Antler": "鹿の角",
    "Dewdrop Leaf": "つゆの葉",
    "Dragonfly": "とんぼ",
    "Dumpling Trio": "三色だんご",
    "Eclair Slice": "エクレア",
    "Egg Tart": "エッグタルト",
    "Evergreen Bow": "もみの木のリボン",
    "Fan Sandal": "扇とサンダル",
    "Fawn Plush": "子鹿のぬいぐるみ",
    "Felt Bird": "フェルトの小鳥",
    "Felt Star": "フェルトの星",
    "Festival Mask": "お祭りのお面",
    "Firefly Jar": "ほたるの瓶",
    "Firefly Lantern": "ほたるランタン",
    "Fireworks": "花火",
    "Flag Charm": "旗のお守り",
    "Flannel Scarf": "フランネルマフラー",
    "Flower Hairpin": "花のかんざし",
    "Flying Penguin": "飛ぶペンギン",
    "Forest Bird": "森の小鳥",
    "Fortune Cookie": "フォーチュンクッキー",
    "Fox Charm": "きつねのお守り",
    "Fox Scarf": "きつねマフラー",
    "Frosted Donut": "アイシングドーナツ",
    "Frosty Mailbox": "霜のついたポスト",
    "Frosty Owl": "霜のフクロウ",
    "Frosty Star": "霜の星",
    "Frosty Teapot": "霜のティーポット",
    "Frosty Window": "霜の窓",
    "Fruit Cup": "フルーツカップ",
    "Garden Snail": "庭のかたつむり",
    "Ghost Cookie": "おばけクッキー",
    "Ghost Lantern": "おばけランタン",
    "Gift Box": "ギフトボックス",
    "Gingerbread": "ジンジャーブレッド",
    "Gold Lantern": "金のとうろう",
    "Goldfish Bag": "金魚すくいの袋",
    "Goldfish Cookie": "金魚クッキー",
    "Goldfish Lantern": "金魚ちょうちん",
    "Goldfish Scoop": "金魚すくい",
    "Grass Tag": "草のタグ",
    "Green Apple": "青りんご",
    "Green Tea": "緑茶",
    "Grilled Mochi": "焼きもち",
    "Halloween Lantern": "ハロウィンランタン",
    "Hammock": "ハンモック",
    "Harvest Mouse": "ハーベストマウス",
    "Heart Bag": "ハートのバッグ",
    "Heart Box": "ハートの箱",
    "Heart Cookie": "ハートクッキー",
    "Heart Lantern": "ハートのランタン",
    "Hedgehog": "ハリネズミ",
    "Holiday Cookie": "ホリデークッキー",
    "Holiday Star": "ホリデースター",
    "Honey Toast": "ハニートースト",
    "Hot Spring Bath": "温泉",
    "Hot Thermos": "あったか水筒",
    "Hydrangea Bloom": "あじさいの花",
    "Hydrangea Lantern": "あじさいランタン",
    "Ice Cream Cone": "アイスクリームコーン",
    "Iced Coffee": "アイスコーヒー",
    "Icicle Bell": "つららのすず",
    "Ink Brush": "筆",
    "Jack-O-Lantern": "ジャックオーランタン",
    "Jam Toast": "ジャムトースト",
    "Jellybean Bag": "ゼリービーンズの袋",
    "Kagami Mochi": "鏡もち",
    "Kite Pup": "たこ犬",
    "Knit Hat": "ニット帽",
    "Knit Mittens": "ニットミトン",
    "Knitted Sock": "編み込み靴下",
    "Lantern Alley": "ちょうちんの小道",
    "Lantern Bear": "ランタンのくま",
    "Lantern Cat": "ちょうちんのねこ",
    "Lantern Owl": "ランタンふくろう",
    "Leaf Boat": "葉っぱのふね",
    "Leaf Coin": "葉っぱのコイン",
    "Leaf Frog": "葉っぱのかえる",
    "Leaf Lantern": "葉のランタン",
    "Leaf Sprout": "若芽",
    "Lemon Slice": "レモンスライス",
    "Lemonade Glass": "レモネードグラス",
    "Lemonade Jar": "レモネードジャー",
    "Letter Bird": "手紙の小鳥",
    "Letter Plane": "手紙ひこうき",
    "Lily Pad Frog": "蓮の葉のかえる",
    "Little Bee": "ちいさなみつばち",
    "Little Crab": "ちいさなかに",
    "Little Penguin": "ちいさなペンギン",
    "Lotus Bloom": "蓮の花",
    "Lotus Lantern": "蓮のランタン",
    "Love Letter": "ラブレター",
    "Lucky Cat": "招き猫",
    "Lucky Coin": "ラッキーコイン",
    "Lucky Envelope": "お年玉袋",
    "Lullaby Sheep": "ねむりひつじ",
    "Maple Acorn": "もみじとどんぐり",
    "Maple Cookie": "メイプルクッキー",
    "Maple Mug": "メイプルマグ",
    "Maple Seed": "もみじの種",
    "Maple Tea": "メイプルティー",
    "Marshmallow": "マシュマロ",
    "Melody Bird": "うたう小鳥",
    "Melon Pan": "メロンパン",
    "Melon Soda": "メロンソーダ",
    "Mikan Basket": "みかんかご",
    "Mini Cactus": "ミニサボテン",
    "Mini Pumpkin": "ミニかぼちゃ",
    "Mistletoe": "ヤドリギ",
    "Mitten Cat": "ミトンのねこ",
    "Mochi Plate": "おもちプレート",
    "Mood Candle": "気分のキャンドル",
    "Moon Cookie": "月のクッキー",
    "Moon Phase Disc": "月相ディスク",
    "Mooncake": "月餅",
    "Moonlit Snack": "月夜のおやつ",
    "Mountain Sunrise": "山の日の出",
    "Mug Cake": "マグカップケーキ",
    "Mushroom Trio": "三つのきのこ",
    "New Year Kite": "新年のたこ",
    "Night Picnic": "夜のピクニック",
    "Notebook Star": "ノートと星",
    "Origami Crane": "折り鶴",
    "Origami Penguin": "折り紙ペンギン",
    "Owl Lantern": "ふくろうランタン",
    "Owl Moon": "月とふくろう",
    "Paper Boat": "紙ぶね",
    "Paper Lantern": "紙ちょうちん",
    "Party Hat": "パーティ帽子",
    "Peach Soda": "ピーチソーダ",
    "Pearl Shell": "真珠の貝",
    "Pencil Star": "鉛筆と星",
    "Picnic Basket": "ピクニックバスケット",
    "Picnic Pup": "ピクニックの子犬",
    "Pine Cone": "まつぼっくり",
    "Pine Fan": "松のうちわ",
    "Pinwheel": "風車",
    "Pixel Apple": "ピクセルりんご",
    "Plum Branch": "梅の枝",
    "Plum Tea": "梅茶",
    "Pocket Map": "ポケット地図",
    "Pocket Watch": "懐中時計",
    "Polar Bear": "しろくま",
    "Popsicle": "アイスキャンディ",
    "Popsicle Stand": "アイス屋台",
    "Pottery Bowl": "陶器のお椀",
    "Pudding Cup": "プリンカップ",
    "Puddle Boot": "水たまり長ぐつ",
    "Puddle Frog": "水たまりかえる",
    "Pumpkin Cookie": "かぼちゃクッキー",
    "Pumpkin Mug": "かぼちゃマグ",
    "Pumpkin Pin": "かぼちゃのピン",
    "Pumpkin Plush": "かぼちゃのぬいぐるみ",
    "Quilt Mug": "キルトのマグ",
    "Rain Bird": "雨の小鳥",
    "Rain Boots": "レインブーツ",
    "Rain Cloud": "雨雲",
    "Rain Diary": "雨の日記",
    "Rain Frog": "雨かえる",
    "Rain Lantern": "雨のランタン",
    "Rain Mittens": "雨のミトン",
    "Rain Mug": "雨のマグ",
    "Rain Notebook": "雨のノート",
    "Rainbow Cap": "レインボーキャップ",
    "Rainbow Notebook": "レインボーノート",
    "Rainbow Window": "虹の窓",
    "Red Boots": "赤いブーツ",
    "Red Lantern": "赤いちょうちん",
    "Red Maple Leaf": "もみじ",
    "Reindeer Plush": "トナカイのぬいぐるみ",
    "Ribbon Chocolate": "リボンチョコレート",
    "Rice Bowl": "ごはん茶碗",
    "Rice Scoop": "しゃもじ",
    "River Stone": "川の石",
    "Rose Letter": "薔薇の手紙",
    "Rose Petals": "薔薇の花びら",
    "Sailboat Bow": "ヨットのリボン",
    "Sakura Cookie": "さくらクッキー",
    "Sakura Letter": "さくらの手紙",
    "Sakura Petal": "桜の花びら",
    "Sandcastle": "砂のお城",
    "Santa Cookie": "サンタクッキー",
    "Santa Hat": "サンタ帽子",
    "Sausage Roll": "ソーセージロール",
    "Scarf Bear": "マフラーのくま",
    "Scarf Penguin": "マフラーのペンギン",
    "School Bag": "ランドセル",
    "School Cap": "通学帽",
    "Sea Bubble": "海のあぶく",
    "Sea Shell": "貝殻",
    "Sea Star": "ヒトデ",
    "Seashell Pin": "貝殻のピン",
    "Seed Packet": "種の袋",
    "Sled": "そり",
    "Slipper Cat": "スリッパのねこ",
    "Smile Cookie": "スマイルクッキー",
    "Smile Mug": "スマイルマグ",
    "Snow Bunny": "雪うさぎ",
    "Snow Cone": "かき氷",
    "Snow Crystal": "雪の結晶",
    "Snow Globe": "スノードーム",
    "Snow Lantern": "雪のとうろう",
    "Snow Rabbit": "雪うさぎ",
    "Soft Cloud": "ふわふわ雲",
    "Songbird Bow": "うたう小鳥のリボン",
    "Spider Cookie": "クモのクッキー",
    "Sprout Mug": "若芽のマグ",
    "Stamp Card": "スタンプカード",
    "Star Charm": "星のお守り",
    "Star Cookie": "星のクッキー",
    "Star Garland": "星のガーランド",
    "Star Lantern": "星のランタン",
    "Star Letter": "星の手紙",
    "Starfish": "ヒトデ",
    "Stocking": "靴下",
    "Straw Hat": "麦わら帽子",
    "Strawberry Bonbon": "いちごボンボン",
    "Strawberry Sandwich": "いちごサンド",
    "Striped Blanket": "ストライプブランケット",
    "Striped Kite": "ストライプのたこ",
    "Study Cat": "勉強ねこ",
    "Summer Yukata Bow": "夏ゆかたの帯",
    "Sun Hat": "サンハット",
    "Sun Sunflower": "太陽とひまわり",
    "Sunflower": "ひまわり",
    "Sunny Cap": "サニーキャップ",
    "Sunset Soda": "夕焼けソーダ",
    "Swan Feather": "白鳥の羽",
    "Sweater Duck": "セーターのアヒル",
    "Tadpole Jar": "おたまじゃくしの瓶",
    "Tanabata Wish": "七夕の願い",
    "Tea Kettle Rain": "ティーケトルと雨",
    "Tea Steam": "お茶の湯気",
    "Teapot Steam": "ティーポットの湯気",
    "Tide Pool Crab": "潮だまりのかに",
    "Tiny Bee": "ちいさなみつばち",
    "Tiny Kite": "ちいさなたこ",
    "Tiny Snowman": "ちいさな雪だるま",
    "Tomato Basket": "トマトのかご",
    "Toy Drum": "おもちゃの太鼓",
    "Trick Ticket": "トリックチケット",
    "Tropical Flower": "南国の花",
    "Tulip Bud": "チューリップのつぼみ",
    "Tulip Ribbon": "チューリップのリボン",
    "Umbrella Bouquet": "傘の花束",
    "Valentine Envelope": "バレンタインの封筒",
    "Walnut Cookie": "くるみクッキー",
    "Warm Scarf": "あったかマフラー",
    "Watermelon Pop": "スイカポップ",
    "Watermelon Slice": "スイカ",
    "Whale Cloud": "くじら雲",
    "Wheat Bundle": "麦の束",
    "Wind Sock": "ふきながし",
    "Window Rainbow": "窓の虹",
    "Winter Candle": "冬のキャンドル",
    "Winter Sparrow": "冬すずめ",
    "Wish Card": "願いごとカード",
    "Witch Boots": "魔女のブーツ",
    "Witch Hat": "魔女の帽子",
    "Wool Beret": "ウールのベレー帽",
    "Wool Hat": "ウールの帽子",
    "Wreath": "リース",
    "Yellow Butterfly": "黄色いちょうちょ",
    "Young Leaf": "若葉",
    # --- Round 2 additions ---
    "Cookie Tin": "クッキー缶",
    "Coral Fish": "サンゴの魚",
    "Coral Starfish": "サンゴのヒトデ",
    "Cozy Teapot": "コージーティーポット",
    "Crescent Cup": "三日月のカップ",
    "Cupid Arrow": "キューピッドの矢",
    "Daffodil Lamp": "すいせんのランプ",
    "Daisy Crown": "デイジーの花冠",
    "Daisy Pin": "デイジーのピン",
    "Dandelion Puff": "たんぽぽの綿毛",
    "Dango Stack": "だんご三兄弟",
    "Denim Overalls": "デニムのオーバーオール",
    "Dew Strawberry": "つゆのいちご",
    "Dolphin Splash": "イルカのしぶき",
    "Dusk Sparrow": "夕暮れのすずめ",
    "Evening Cicada": "ひぐらし",
    "Fallen Leaf Boot": "落ち葉のブーツ",
    "Farewell Bouquet": "おわかれの花束",
    "Fern Sprig": "シダの小枝",
    "Festival Cotton Candy": "お祭りのわたあめ",
    "Festival Fan": "お祭り扇子",
    "Fir Cookie": "もみの木クッキー",
    "Firefly Sprout": "ほたるの若芽",
    "Firework Pin": "花火のピン",
    "Fireworks Shell": "打ち上げ花火",
    "First Sunrise": "初日の出",
    "Float Ring": "浮き輪",
    "Flower Cart": "花のカート",
    "Flower Wagon": "花のワゴン",
    "Fox Mitten": "きつねミトン",
    "Fox Postcard": "きつねのポストカード",
    "Fresh Tea": "新茶",
    "Frog Cap": "かえる帽子",
    "Frog Umbrella": "かえるの傘",
    "Frost Window": "霜の窓",
    "Garden Gloves": "ガーデン手袋",
    "Ghost Balloon": "おばけ風船",
    "Ghost Sheet": "おばけシーツ",
    "Gingerbread Star": "ジンジャーブレッドの星",
    "Graduation Cap": "卒業帽",
    "Grape Bunch": "ぶどうのふさ",
    "Green Bicycle": "緑の自転車",
    "Hammock Cat": "ハンモックのねこ",
    "Hanging Mobile Drop": "つるしモビール",
    "Harvest Pie": "収穫パイ",
    "Harvest Wagon": "収穫ワゴン",
    "Haunted House": "おばけ屋敷",
    "Heart Balloon": "ハート風船",
    "Hedgehog Apple": "ハリネズミりんご",
    "Hina Dolls": "ひな人形",
    "Holiday Train": "ホリデー列車",
    "Holly Branch": "ヒイラギの枝",
    "Hot Cocoa": "ホットココア",
    "Hydrangea": "あじさい",
    "Hydrangea Basket": "あじさいバスケット",
    "Ice Cream Cart": "アイスクリーム屋台",
    "Iris Bloom": "あやめの花",
    "Jack O Lantern Pie": "ジャックオーランタンパイ",
    "Jam Jar": "ジャムの瓶",
    "Jingle Bell": "ジングルベル",
    "Kabuto Helmet": "かぶと",
    "Knit Basket": "ニットバスケット",
    "Lace Cupcake": "レースカップケーキ",
    "Ladybug Cap": "てんとう虫キャップ",
    "Ladybug Picnic": "てんとう虫のピクニック",
    "Lamb Plush": "ひつじのぬいぐるみ",
    "Lantern Book": "ランタンの本",
    "Lantern Bug": "ランタン虫",
    "Lantern Crow": "ランタンのカラス",
    "Lavender Rain": "ラベンダーの雨",
    "Leap Frog": "とびかえる",
    "Lemon Raincoat": "レモンレインコート",
    "Lemon Soda": "レモンソーダ",
    "Letter Note": "手紙のメモ",
    "Lily Cup": "ユリのカップ",
    "Little Monster": "ちいさなモンスター",
    "Loaf Bread": "ちぎりパン",
    "Mango Parfait": "マンゴーパフェ",
    "Maple Leaf": "もみじの葉",
    "Market Radish": "市場のだいこん",
    "Marshmallow Cup": "マシュマロカップ",
    "Mask Cat": "お面のねこ",
    "Midnight Candle": "真夜中のキャンドル",
    "Misty Window": "霧の窓",
    "Mitten Pair": "ミトン一対",
    "Moon Broom": "月のほうき",
    "Moon Fox": "月のきつね",
    "Moon Jelly": "月のクラゲ",
    "Moon Lantern": "月のランタン",
    "Moon Rabbit": "月のうさぎ",
    "Moon Tea": "月のお茶",
    "Moonlit Cabin": "月夜の山小屋",
    "Moss Mushroom": "苔のきのこ",
    "Mountain Beetle": "山のかぶとむし",
    "Mushroom Basket": "きのこバスケット",
    "Mushroom House": "きのこの家",
    "Mushroom Stool": "きのこの腰かけ",
    "Music Box": "オルゴール",
    "Nest Egg": "巣のたまご",
    "Night Bonfire": "夜のたき火",
    "Night Sparkler": "夜の線香花火",
    "Notebook Duck": "ノートとアヒル",
    "Notebook Flower": "ノートと花",
    "Ocean Jellyfish": "海のクラゲ",
    "Ocean Postcard": "海のポストカード",
    "Ornament Cat": "オーナメントのねこ",
    "Owl Bookmark": "ふくろうのしおり",
    "Owl Perch": "ふくろうの止まり木",
    "Pampas Grass": "すすき",
    "Paper Crane": "折り鶴",
    "Paper Fan": "うちわ",
    "Party Cupcake": "パーティカップケーキ",
    "Pastel Camera": "パステルカメラ",
    "Pastel Macaron": "パステルマカロン",
    "Pastel Umbrella": "パステルの傘",
    "Peach Blossom": "桃の花",
    "Pear Tart": "なしのタルト",
    "Persimmon Branch": "柿の枝",
    "Picnic Kettle": "ピクニックケトル",
    "Picnic Thermos": "ピクニック水筒",
    "Pineapple Drink": "パイナップルドリンク",
    "Pinecone Lamp": "まつぼっくりランプ",
    "Plaid Blanket": "チェック柄ブランケット",
    "Plant Tag": "植物のタグ",
    "Polar Bear Scarf": "しろくまのマフラー",
    "Present Box": "プレゼントボックス",
    "Puddle Duck": "水たまりのアヒル",
    "Pumpkin Cocoa": "かぼちゃココア",
    "Pumpkin Lantern": "かぼちゃランタン",
    "Pumpkin Wagon": "かぼちゃワゴン",
    "Purple Potion": "むらさきの薬",
    "Rain Chime": "雨のチャイム",
    "Rain Window": "雨の窓",
    "Rainbow Pin": "レインボーピン",
    "Raindrop": "あめつぶ",
    "Raindrop Bell": "雨つぶのすず",
    "Rainy Cat": "雨ねこ",
    "Rainy Teacup": "雨のティーカップ",
    "Ramune Bottle": "ラムネ瓶",
    "Raven Letter": "カラスの手紙",
    "Reading Cat": "読書ねこ",
    "Reindeer Mug": "トナカイマグ",
    "Ribbon Badge": "リボンのバッジ",
    "Ribbon Bouquet": "リボンの花束",
    "Ribbon Gift": "リボンのギフト",
    "Ribbon Scissors": "リボンばさみ",
    "Rice Ball Picnic": "おにぎりピクニック",
    "River Fish": "川魚",
    "Roasted Sweet Potato": "焼きいも",
    "Robin Branch": "コマドリの枝",
    "Sailboat": "ヨット",
    "Sakura Branch": "桜の枝",
    "Sakura Lantern": "桜のランタン",
    "Sandwich Box": "サンドイッチボックス",
    "School Satchel": "通学かばん",
    "Seashell Crown": "貝殻の冠",
    "Seashell Note": "貝殻のメモ",
    "Seedling Pot": "苗の鉢",
    "Shaved Ice": "かき氷",
    "Shaved Ice Bear": "かき氷くま",
    "Shell Bracelet": "貝殻のブレスレット",
    "Shooting Star": "流れ星",
    "Skeleton Key": "がいこつのカギ",
    "Sky Whale": "空のくじら",
    "Sled Bell": "そりのすず",
    "Snail Leaf": "かたつむりの葉",
    "Snowdrop Bloom": "スノードロップの花",
    "Snowflake Lantern": "雪の結晶ランタン",
    "Snowman": "雪だるま",
    "Songbird": "うた鳥",
    "Soup Pot": "スープなべ",
    "Spell Book": "魔法の本",
    "Spider Teacup": "クモのティーカップ",
    "Spring Puddle": "春の水たまり",
    "Spring Teapot": "春のティーポット",
    "Sprout Boots": "若芽ブーツ",
    "Squirrel Nut": "リスのどんぐり",
    "Squirrel Scarf": "リスのマフラー",
    "Star Bookmark": "星のしおり",
    "Star Cloak": "星のマント",
    "Star Topper": "星のトッパー",
    "Stargazing Tent": "星見テント",
    "Starlight Bow": "星明かりのリボン",
}


def collect_required_keys() -> set[str]:
    """Collect all l10n keys referenced by daily content + journey JSONs."""
    keys: set[str] = set()
    # Catalog
    catalog = json.loads((root / "Journey" / "monthly_daily_events.json").read_text())
    LOC_FIELDS = {
        "titleKey", "subtitleKey", "albumTitleKey", "bannerKey",
        "archiveTitleKey", "archiveSubtitleKey",
        "rewardTitleKey", "rewardSubtitleKey",
        "categoryKey", "difficultyKey",
    }

    def walk(obj):
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, str) and k in LOC_FIELDS:
                    keys.add(v)
                else:
                    walk(v)
        elif isinstance(obj, list):
            for x in obj:
                walk(x)
    walk(catalog)
    # Daily level files
    for p in sorted(root.glob("Levels/daily_*.json")):
        obj = json.loads(p.read_text())
        for src in ("titleKey", "title"):
            if isinstance(obj.get(src), str):
                keys.add(obj[src])
        for src in ("difficultyKey", "difficulty"):
            if isinstance(obj.get(src), str):
                keys.add(obj[src])
        for src in ("categoryKey", "category"):
            if isinstance(obj.get(src), str):
                keys.add(obj[src])
    return keys


def main() -> int:
    required = collect_required_keys()
    xc = json.loads(xc_path.read_text())
    ss = xc.setdefault("strings", {})

    added = 0
    skipped_existing = 0
    missing_translation = []
    for key in sorted(required):
        if key in ss:
            skipped_existing += 1
            continue
        ja = TRANSLATIONS_JA.get(key)
        if ja is None:
            missing_translation.append(key)
            continue
        ss[key] = {
            "comment": "Auto-added by patch_daily_localizations.py for daily challenge content.",
            "extractionState": "manual",
            "localizations": {
                "en": {
                    "stringUnit": {
                        "state": "translated",
                        "value": key,
                    }
                },
                "ja": {
                    "stringUnit": {
                        "state": "translated",
                        "value": ja,
                    }
                },
            },
        }
        added += 1

    xc_path.write_text(json.dumps(xc, indent=2, ensure_ascii=False) + "\n")

    print(f"Required l10n keys (from JSON content): {len(required)}")
    print(f"Already in xcstrings, skipped:           {skipped_existing}")
    print(f"Added en+ja entries:                     {added}")
    print(f"Missing ja translation (NOT added):      {len(missing_translation)}")
    for k in missing_translation:
        print("  - " + repr(k))
    if missing_translation:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
